version: '3.8'

services:  # <-- All services MUST be nested here
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - app

  app:
    build: ./app
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=appuser
      - DB_PASSWORD=apppass
      - DB_NAME=mydb
    networks:
      - app-network
      - db-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:  # <-- This MUST be under the `services` key
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uappuser", "-papppass"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:

networks:
  app-network:
  db-network:
    internal: true
